"""Generate compact, reproducible ECG profiles for the browser demo.

The output is synthetic research-demo data, not a clinical recording.
Run from the project root after installing scripts/requirements-neurokit.txt.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import neurokit2 as nk
import numpy as np


PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = PROJECT_ROOT / "app" / "neurokitProfiles.ts"
SAMPLING_RATE = 128
DURATION_SECONDS = 20
DISPLAY_SECONDS = 8
DISPLAY_SAMPLES = 320
RATES = [60, 65, 68, 72, 74, 77, 80, 84, 88, 92, 96]


def compact(value: float) -> float:
    return round(float(value), 4)


def build_profile(bpm: int, index: int) -> dict[str, object]:
    variability = max(1.2, 5.5 - (bpm - 60) * 0.075)
    raw = nk.ecg_simulate(
        duration=DURATION_SECONDS,
        sampling_rate=SAMPLING_RATE,
        heart_rate=bpm,
        heart_rate_std=variability,
        noise=0.012,
        method="ecgsyn",
        random_state=4100 + index,
    )
    cleaned = nk.ecg_clean(raw, sampling_rate=SAMPLING_RATE, method="neurokit")
    _, peak_info = nk.ecg_peaks(cleaned, sampling_rate=SAMPLING_RATE, method="neurokit")
    peaks = np.asarray(peak_info["ECG_R_Peaks"], dtype=float)
    rr_ms = np.diff(peaks) / SAMPLING_RATE * 1000
    rr_diff = np.diff(rr_ms)
    rmssd = math.sqrt(float(np.mean(np.square(rr_diff)))) if rr_diff.size else 0.0

    window = np.asarray(cleaned[-DISPLAY_SECONDS * SAMPLING_RATE :], dtype=float)
    low, high = np.percentile(window, [1, 99])
    scale = max(abs(low), abs(high), 1e-6)
    normalized = np.clip(window / scale, -1.1, 1.1)
    source_x = np.linspace(0, 1, normalized.size)
    display_x = np.linspace(0, 1, DISPLAY_SAMPLES)
    samples = np.interp(display_x, source_x, normalized)

    return {
        "bpm": bpm,
        "meanRrMs": round(float(np.mean(rr_ms))) if rr_ms.size else round(60000 / bpm),
        "rmssdMs": round(rmssd),
        "samples": [compact(value) for value in samples],
    }


def main() -> None:
    profiles = [build_profile(rate, index) for index, rate in enumerate(RATES)]
    payload = json.dumps(profiles, separators=(",", ":"))
    content = f"""// Generated by scripts/generate_neurokit_profiles.py using NeuroKit2 {nk.__version__}.
// Synthetic ECGSYN signals for interaction prototyping; not clinical data.

export type NeurokitProfile = {{
  bpm: number;
  meanRrMs: number;
  rmssdMs: number;
  samples: readonly number[];
}};

export const neurokitVersion = '{nk.__version__}';
export const neurokitProfiles = {payload} as const satisfies readonly NeurokitProfile[];

export function nearestNeurokitProfile(bpm: number): NeurokitProfile {{
  return neurokitProfiles.reduce<NeurokitProfile>((nearest, profile) =>
    Math.abs(profile.bpm - bpm) < Math.abs(nearest.bpm - bpm) ? profile : nearest,
  neurokitProfiles[0]);
}}
"""
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {len(profiles)} profiles to {OUTPUT}")


if __name__ == "__main__":
    main()
